### PR TITLE
Issue110 - Adding context to error instead of unwrap

### PR DESCRIPTION
**Pull request by oren0e**
Re https://github.com/metalbear-co/mirrord/issues/110
I'm not sure if this is it or you had something more complex in mind...
btw - it's hard to test changes locally without some kind of a guide/documentation on how to setup a proper local testing env

### CODE REVIEW

**Comment by aviramha** [comment]
Thanks for the contribution. Please add a CHANGELOG entry and update the branch.
Regarding testing locally - yes.. I agree, it's very painful and we've yet have found the best practice even among the team as the "full" case is very complex and requires a Kubernetes cluster. If you have any suggestion on how to solve it we'd be glad to implement/think about it.

**Comment by oren0e** [comment]
@aviramha Is this even still relevant (I'm asking because I see https://github.com/metalbear-co/mirrord/pull/170 was merged)

**Comment by aviramha** [comment]
@oren0e yeah it's different lines.. I think @camerondurham skipped on purpose to not conflict your PR :)

**Comment by oren0e** [comment]
@aviramha ready for review

**Review by aviramha — APPROVED** [review]

**Comment by aviramha** [comment]
Thank you!

**Pull request merged**
