### PR TITLE
[Merged by Bors] - layer/agent: add control of network interface to use

### PR DESCRIPTION
**Pull request by aviramha**

### CODE REVIEW

**Review by t4lz — APPROVED** [review]
Looks good!

Question: Why not a CLI argument also?
General thought: looks like ephemeral container and job pod creation could share some code (but it should not hold back this PR).

**Comment by t4lz** [comment]
Ok looks like the tests need to be adapted and the CHANGELOG formatted.

**Comment by aviramha** [comment]
> Question: Why not a CLI argument also? 
Thanks! 
I don't see how it's relevant for most people so I prefer less arguments.

> General thought: looks like ephemeral container and job pod creation could share some code (but it should not hold back this PR).
Agree

**Review by t4lz — CHANGES_REQUESTED** [review]
Regenerate schema please!
https://github.com/metalbear-co/mirrord/blob/main/mirrord/config/src/lib.rs#L18

**Review by t4lz — APPROVED** [review]
Doesn't have to be in the config schema for now.

**Pull request closed without merging**
