### PR TITLE
Fix case were agent log message causes startup failure

### PR DESCRIPTION
**Pull request by aviramha**

### CODE REVIEW

**Review by t4lz — COMMENTED** [review]
The error handling is just an optional suggestion. Let me know if you disagree about the timeout.

**Comment by aviramha** [comment]
> The error handling is just an optional suggestion. Let me know if you disagree about the timeout.

 The log would emit a clear message anyway (debug representation so we know exactly what we had received)..
The timeout is a good catch.

**Review by t4lz — APPROVED** [review]
Looks fine. If we're using the same error variant for all scenarios, I suggest changing its name from `AgentClosedConnection` (as that might be a bit confusing when that is not what happen) to `NoPong`, and also changing that error's text (in `#[error("...")]`) to `Did not get a 'pong' from the agent: could be a timeout, an invalid message, or the agent closed the connection`.

**Review by t4lz — APPROVED** [review]
thanks

**Pull request merged**
