### PR TITLE
Set MIRRORD_AGENT_IMAGE for vscode e2e and tidy actions

### PR DESCRIPTION
**Pull request by infiniteregrets**

### CODE REVIEW

**Comment by aviramha** [comment]
qq: how did you verify it actually uses the `test` image?

**Comment by infiniteregrets** [comment]
> qq: how did you verify it actually uses the `test` image?

i did a simple test:

ran :  MIRRORD_AGENT_IMAGE="test" KUBE_SERVICE=localhost:30000 POD_TO_SELECT=py-serv-deployment-ff89b5974-dhl2q node out/tests/runTests.js
didn't build the image beforehand, assuming it would fail:

tests are bailed on debugging and agent pod logs:

mehularora@Mehuls-Air mirrord % kubectl describe pod mirrord-agent-t4yxqj5yt6-dn29z
Name:             mirrord-agent-t4yxqj5yt6-dn29z
Namespace:        default
Priority:         0
Service Account:  default
Node:             docker-desktop/192.168.65.4
Start Time:       Sun, 04 Jun 2023 11:28:41 -0400
Labels:           app=mirrord
                  controller-uid=3f43c892-3a25-4ba1-bf55-3eee25a831ef
                  job-name=mirrord-agent-t4yxqj5yt6
Annotations:      linkerd.io/inject: disabled
                  sidecar.istio.io/inject: false
Status:           Pending
IP:               10.1.3.49
IPs:
  IP:           10.1.3.49
Controlled By:  Job/mirrord-agent-t4yxqj5yt6
Containers:
  mirrord-agent:
    Container ID:  
    Image:         test
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      ./mirrord-agent
      -l
      46451
      --container-id
      6437100db7331a00d3f9d25c8b9dd3d0810b0016f01fd71b5c8ebc21f75de9c1
      --container-runtime
      docker
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:     1m
      memory:  1Mi
    Environment:
      RUST_LOG:                                 info
      MIRRORD_AGENT_STEALER_FLUSH_CONNECTIONS:  true
    Mounts:
      /host/run from hostrun (rw)
      /host/var from hostvar (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-w269w (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  hostrun:
    Type:          HostPath (bare host directory volume)
    Path:          /run
    HostPathType:  
  hostvar:
    Type:          HostPath (bare host directory volume)
    Path:          /var
    HostPathType:  
  kube-api-access-w269w:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason   Age                From     Message
  ----     ------   ----               ----     -------
  Normal   BackOff  21s (x2 over 23s)  kubelet  Back-off pulling image "test"
  Warning  Failed   21s (x2 over 23s)  kubelet  Error: ImagePullBackOff
  Normal   Pulling  10s (x2 over 23s)  kubelet  Pulling image "test"
  Warning  Failed   10s (x2 over 23s)  kubelet  Failed to pull image "test": rpc error: code = Unknown desc = Error response from daemon: pull access denied for test, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
  Warning  Failed   10s (x2 over 23s)  kubelet  Error: ErrImagePull

**Comment by aviramha** [comment]
but in ci we use `npm run test`?

**Review by aviramha — APPROVED** [review]
Good job!

**Comment by infiniteregrets** [comment]
> but in ci we use `npm run test`?

the test script in package.json is essentially the same, `npm run pretest && node out/tests/runTests.js`. I will run a quick test with npm run test just to be sure

**Comment by infiniteregrets** [comment]
> > but in ci we use `npm run test`?
> 
> the test script in package.json is essentially the same, `npm run pretest && node out/tests/runTests.js`. I will run a quick test with npm run test just to be sure

works just the same, merging

**Pull request merged**
