### PR TITLE
Fixed fork and gethostname with `MIRRORD_LAYER_TRACE_ONLY`

### PR DESCRIPTION
**Pull request by Razz4780**
`fork` and `gethostname` detours still tried to talk to the internal proxy

### CODE REVIEW

**Comment by aviramha** [comment]
Need to fix conflicts.

**Comment by aviramha** [comment]
@Razz4780 let's decide whether to merge it or close it please :)

**Comment by Razz4780** [comment]
> @Razz4780 let's decide whether to merge it or close it please :)

Sorry, completely forgot about this :sweat_smile: 
Gonna fix it today

**Comment by Razz4780** [comment]
Replaced with #2160

**Pull request closed without merging**
