### PR TITLE
[Merged by Bors] - Fix errors when setting envars when debugging Kotlin app

### PR DESCRIPTION
**Pull request by jamowei**
Fix double showing of `MirrordKubeDialog` and errors occurring when setting envars when debug a Kotlin app.
image

### CODE REVIEW

**Review by infiniteregrets — APPROVED** [review]
Thanks for finding this bug @jamowei!

**Comment by aviramha** [comment]
Thanks!!

**Comment by infiniteregrets** [comment]
Just to confirm, did you try this with any other applications besides Kotlin? If so does this happen anywhere else?

**Pull request closed without merging**
