### PR TITLE
Enable intproxy logs by default.

### PR DESCRIPTION
**Pull request by meowjesty**
- Issue: #2750

### CODE REVIEW

**Comment by Razz4780** [comment]
Gotta make sure that `info` level produces informative logs on layer<->intproxy<->agent requests and responses, except messages that only transfer data (like in file or remote connections reads/writes)

**Comment by aviramha** [comment]
@Razz4780 to be on the same page - you want to check there's no spam, not to add more messages, right?

**Comment by Razz4780** [comment]
> @Razz4780 to be on the same page - you want to check there's no spam, not to add more messages, right?

I think this will only require moving some message from `trace` to `info`

**Comment by aviramha** [comment]
> > @Razz4780 to be on the same page - you want to check there's no spam, not to add more messages, right?
> 
> I think this will only require moving some message from `trace` to `info`

I'm quite against this - I think it'd be premature optimization - I'd guess that most important stuff are getting errors/warnings and if we need to add more things let's do it when we realize that.

**Review by Razz4780 — APPROVED** [review]

**Pull request merged**
