### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by kianmeng**

### CODE REVIEW

**Comment by aviramha** [comment]
Thanks for this! Can you please add a CHANGELOG entry? Probably under `Fixed`

**Comment by kianmeng** [comment]
@aviramha Done.

**Review by aviramha — APPROVED** [review]

**Comment by aviramha** [comment]
Thank you!

**Comment by kianmeng** [comment]
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face:

**Pull request merged**
