### PR TITLE
Fix dns test

### LINKED ISSUE #224: Fix test_remote_dns_enabled_works E2E
@abhirag noticed that in the test we don't run the correct script which is weird that it still succeeds. Need to understand why the test succeeds and fix the test.

### PR DESCRIPTION
**Pull request by infiniteregrets**
We were running the test with `-d true` which is probably the reason it was not erroring out
Closes #224

### CODE REVIEW

**Comment by infiniteregrets** [comment]
@aviramha On a side note while testing in a different branch, I noticed that we are creating temporary directories twice for fileops test. If I remove `get_shared_lib_path` function, the tests get very flaky

**Comment by aviramha** [comment]
> @aviramha On a side note while testing in a different branch, I noticed that we are creating temporary directories twice for fileops test. If I remove `get_shared_lib_path` function, the tests get very flaky

I think it's intended? Why wouldn't we want different temporary directories?

**Review by aviramha — APPROVED** [review]

**Comment by aviramha** [comment]
Took the liberty of reverting the random directory name change. Merging. Thanks!

**Comment by infiniteregrets** [comment]
@aviramha are we not already doing that here?
```rs
let temp_dir = tempdir::TempDir::new("test").unwrap();
        let mut mirrord_args = vec![
            "exec",
            "--pod-name",
            pod_name,
            "-c",
            "--extract-path",
            temp_dir.path().to_str().unwrap(),
        ];
```

**Comment by aviramha** [comment]
Woops. You're correct - but this might re-use the same path (atleast from what I've seen) so maybe we should support providing it as a parameter to `run`

**Pull request merged**
