### PR TITLE
Sync layer refactor

### LINKED ISSUE #1952: Drop tokio runtime from layer
Following #1946 #1618 #1948 #1951 
I think the solution is to get rid of the tokio runtime, and drop async stuff from the layer.
The design I had in mind
1. Create a struct that is responsible for decoding/encoding messages to the internalproxy
2. Use that struct for sending messages, when expecting responses it should have some sort of a "mini runtime" that reads messages until it receives the expected response (and stores unexpected responses, if there are threads waiting for it)
3. Split logic that happens in layer from logic that happens on internal proxy - all the listening/mirror socket stuff should happen in layer, but the actual connection should happen from internal proxy, since we won't have a thread to trigger connections from.
4. When an incoming connection happens, the internal proxy would connect to the layer "mirror" socket, then the layer can send a request to read the connection info from the internal proxy, to do the address manipulation logic.
5. The internal proxy might need to have a "global" state shared among different layer instances, for fork situations #864 
6. When outgoing connection happens, it will actually connect to the internal proxy socket, then it will do the forwarding. (with address manipulation)

Some initial drafts I had:
```rs
/// Message that originates from a layer hook, that needs some logic
/// in the internal proxy.
#[derive(Encode, Decode, Debug, PartialEq, Eq, Clone)]
pub enum HookMessage {}

/// Message that is an answer to a hook message.
#[derive(Encode, Decode, Debug, PartialEq, Eq, Clone)]
pub enum HookResponse {}

/// Layer to internal proxy messages
#[derive(Encode, Decode, Debug, PartialEq, Eq, Clone)]
pub enum LayerToProxyMessage {
    /// Message that is just forwarded to the agent.
    Upstream(ClientMessage),
    /// Hook originated message that we should handle
    Hook(HookMessage),
}

/// Messages from internal proxy to layer
#[derive(Encode, Decode, Debug, PartialEq, Eq, Clone)]
pub enum ProxyToLayerMessage {
    /// Messages that are passed as is from the agent.
    Downstream(DaemonMessage),
    /// Responses to hook messages
    HookResponse(HookResponse),
}
```

### PR DESCRIPTION
**Pull request by Razz4780**
Closes #1952 #1946 #1618 

New PR, because CI is broken in the old one #1960 

1. New crate `mirrord-intproxy`. Contains `IntProxy` - structure encapsulating proxy logic between one agent and multiple layer instances (originating from one ancestor - forks).
2. Changed `mirrord-console`. Now it exposes two kinds of loggers - async (spawns background `tokio::task`, usable in cli) and sync (no extra threads, just a `TcpStream` under a `Mutex`, usable in layer).
3. New layer does not spawn any extra threads at all. Communicates with the `IntProxy` using a global `TcpStream` under a `Mutex`.

### CODE REVIEW

**Comment by t4lz** [comment]
> New PR, because CI is broken in the old one

If nothing happens here as well - maybe try resolving conflicts?

**Comment by t4lz** [comment]
Debugging with this branch made me realise: now that a lot of the logic is in the intproxy, it would be very helpful to have a convenient way to get logs from the intproxy - maybe an option to write them to a file?

If it's not a 2 minute, 5 line change - it should be a separate issue though, in order not to delay merging this.

**Comment by Razz4780** [comment]
> Debugging with this branch made me realise: now that a lot of the logic is in the intproxy, it would be very helpful to have a convenient way to get logs from the intproxy - maybe an option to write them to a file?
> 
> If it's not a 2 minute, 5 line change - it should be a separate issue though, in order not to delay merging this.

Hmm, you should be able to see them in `mirrord-console`.
We have some code in the CLI that prevents intproxy from printing logs to stderr, so it doesn't mangle user app's output. Maybe we can remove it? After all, layer also prints logs to stderr

**Comment by t4lz** [comment]
fair enough, mirrord-console is a solution. The intproxy's stderr is redirected to `/dev/null` as part of its daemonization, let's leave it like that.

**Review by t4lz — APPROVED** [review]
it's time

**Pull request merged**
