### PR TITLE
Fix for polling on bad fd (tokio), with uvicorn reload

### LINKED ISSUE #1618: uvicorn with reload crashes
### Bug Description

When running a FastAPI app using Uvicorn and mirrord enabled the process gets tokio errors

### Steps to Reproduce

Create a FastAPI + Uvicorn app from PyCharm template, run it using mirrord.

### Backtrace

```shell
INFO:     Will watch for changes in these directories: ['/Users/aviramhassan/PycharmProjects/fastApiProject1']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [49235] using WatchFiles
thread 'tokio-runtime-worker' panicked at 'unexpected error when polling the I/O driver: Os { code: 9, kind: Uncategorized, message: "Bad file descriptor" }', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/io/mod.rs:180:23
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'unexpected error when polling the I/O driver: Os { code: 9, kind: Uncategorized, message: "Bad file descriptor" }', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/io/mod.rs:180:23
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
INFO:     Started server process [49238]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
```

### Relevant Logs

_No response_

### Your operating system and version

macOS M1

### Local process

python 3.10

### Local process version

_No response_

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by infiniteregrets**
wip to fix #1618

### CODE REVIEW

**Comment by infiniteregrets** [comment]
its quite weird whats going on here, adding else block fixes the polling issue but now the channel has None values?

```
INFO:     Started reloader process [30798] using WatchFiles
2023-09-17T02:25:16.822011Z  INFO ThreadId(01) mirrord_layer: Initializing mirrord-layer!
2023-09-17T02:25:16.823108Z  INFO ThreadId(01) mirrord_layer: Initializing mirrord-layer!
2023-09-17T02:25:16.832788Z  INFO ThreadId(03) mirrord_layer: Received hook message: None
thread '<unnamed>' panicked at mirrord/layer/src/lib.rs:826:56:
called `Option::unwrap()` on a `None` value
stack backtrace:
2023-09-17T02:25:16.832985Z  INFO ThreadId(01) mirrord_layer::common: Sending hook message: Tcp(
    Close(
        8000,
    ),
)
```

**Comment by aviramha** [comment]
> its quite weird whats going on here, adding else block fixes the polling issue but now the channel has None values? the message to be sent here is the `Close`, but the channel received a None before `Close` as `socket.close` cant get the sender and fails on `Err(CannotGetHookSender)`?

Yes, because you changed it so it doesn't set it when it's not set so it's None

**Comment by infiniteregrets** [comment]
> > its quite weird whats going on here, adding else block fixes the polling issue but now the channel has None values? the message to be sent here is the `Close`, but the channel received a None before `Close` as `socket.close` cant get the sender and fails on `Err(CannotGetHookSender)`?
> 
> Yes, because you changed it so it doesn't set it when it's not set so it's None

yeah I realized that, question: why did we have to leak the sender in the first place on forks?

**Comment by aviramha** [comment]
Because the `Drop` implementation didn't work post-fork.

**Comment by infiniteregrets** [comment]
> Because the `Drop` implementation didn't work post-fork.

from my understanding, i think it is the case that the old sender is being used to send the message after its forgotten, maybe we should keep a hashmap of hook_senders mapping each to parent/child and blocking_sends can lookup the correct sender by thread id?

**Comment by aviramha** [comment]
I have a solution for this - I'll try to implement it soon.
The idea is to re-use the sender/receiver, as it should be okay to re-use between runtimes. On fork, we would call a message to hooksender that will send us back the receiver, then we pass it.

**Pull request closed without merging**
